name: Update chains preconfigured

on:
  schedule:
    - cron: '0 8 1/3 * *'
  workflow_dispatch:


permissions:
  contents: write
  pull-requests: write

jobs:
  update-preconfigured:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository to Master branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: üõ† Set up actual paths
        uses: ./.github/workflows/setup-path

      - name: ‚öôÔ∏è Install dependencies
        run: make init

      - name: ü¶æ Update files and data in chains preconfigured
        run: make update-chains-preconfigured

      - name: Make Pull Request
        uses: ./.github/workflows/make-pull-request
        with:
          commit-files: chains/**
          commit-message: Update preconfigured chains
          app-id: ${{ secrets.PR_APP_ID}}
          app-token: ${{ secrets.PR_APP_TOKEN}}
          pr-reviewer: ${{ env.PR_REVIEWER }}
          branch-name: update-preconfigured-chains
          pr-title: üÜô Update preconfigured chains
          pr-body: This PR was generated automatically ü§ñ
          pr-base: master

  alert:
    runs-on: ubuntu-latest
    needs: update-preconfigured
    if: always() && (needs.update-preconfigured.result == 'failure')
    env:
      GITHUB_WORKFLOW_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
    steps:
      - name: Report
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Preconfigured update workflow failed, lets check:

            Failed run:
            ${{ env.GITHUB_WORKFLOW_URL }}
